services:
  api:
    build: .
    container_name: aneurysm-api
    ports:
      - "8045:8045"
    volumes:
      - .:/app
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - aneurysm_network

networks:
  aneurysm_network:
    driver: bridge
